# Generated by Django 5.0.6 on 2024-07-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_honersandawards_publication_researchinterests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_twitter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_website',
        ),
    ]
